### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by nodesocket** [pm2-hive/pm2-syslog#3]
Don't think this is working.

Node 0.12.7

Still see `healthy-out-1.log` files being written, and nothing showing up in syslog via Papertrail.

Running `pm2 logs` shows:

```
pm2-syslog-2 { type: 'axm:monitor',
  data: { 'Loop delay': { value: '0.55ms', agg_type: 'avg' } } }
pm2-syslog-2 { type: 'axm:monitor',
  data: { 'Loop delay': { value: '0.55ms', agg_type: 'avg' } } }
healthy-0 [2015-07-31 23:07:38.647] "HTTP/1.1 GET http://52.8.106.214/health" 200 0.044
pm2-syslog-2 { type: 'axm:monitor',
  data: { 'Loop delay': { value: '0.55ms', agg_type: 'avg' } } }
```

**Comment by montaro** [comment]
+1

**Comment by nodesocket** [comment]
Really like to get this working, only core service that does not log to syslog for us.

**Comment by adamsea** [comment]
+1

**Comment by Unitech** [comment]
PR welcome, the module is [20 lines long](https://github.com/pm2-hive/pm2-syslog/blob/master/app.js)

**Comment by Unitech** [comment]
Module fixed please refer to README.md
